{% set version = "0.11.2" %}

package:
    name: owslib
    version: {{ version }}

source:
    fn: OWSLib-{{ version }}.tar.gz
    url: https://github.com/geopython/OWSLib/archive/{{ version }}.tar.gz
    sha256: df3a3a40b57b9b53c1dfbc8b27388453e2f92ed008fadda883a8376d67882a6a

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - python-dateutil
        - pytz
        - requests
        - pyproj
        - lxml

test:
    imports:
        - owslib.coverage
        - owslib.waterml
        - owslib.swe.observation
        - owslib.swe.sensor
        - owslib
        - owslib.feature
        - owslib.swe

about:
    home: https://geopython.github.io/OWSLib
    license: BSD 3-Clause
    summary: 'OGC Web Service utility library.'

extra:
    recipe-maintainers:
        - kalxas
        - tomkralidis
        - pelson
        - ocefpaf
