
{% set name = "OWSLib" %}
{% set version = "0.34.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/geopython/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: ea3c0a74bda00dd1760acfe5db87a0b02e1b7c201646fa4d2f93f35842451ea5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - lxml
    - python-dateutil
    - pyyaml
    - requests

test:
  source_files:
    - tests
  imports:
    - owslib
    - owslib.coverage
    - owslib.coverage.wcsBase
    - owslib.crs
    - owslib.csw
    - owslib.dif
    - owslib.etree
    - owslib.feature
    - owslib.feature.common
    - owslib.feature.postrequest
    - owslib.feature.schema
    - owslib.fes
    - owslib.fes2
    - owslib.fgdc
    - owslib.gm03
    - owslib.gml
    - owslib.iso
    - owslib.iso3
    - owslib.map.common
    - owslib.map.wms130
    - owslib.namespaces
    - owslib.ogcapi
    - owslib.ogcapi.connectedsystems
    - owslib.ogcapi.coverages
    - owslib.ogcapi.edr
    - owslib.ogcapi.features
    - owslib.ogcapi.maps
    - owslib.ogcapi.processes
    - owslib.ogcapi.records
    - owslib.opensearch
    - owslib.ows
    - owslib.owscontext.atom
    - owslib.owscontext.common
    - owslib.owscontext.core
    - owslib.owscontext.geojson
    - owslib.sos
    - owslib.swe.common
    - owslib.swe.observation.om
    - owslib.swe.observation.waterml2
    - owslib.util
    - owslib.waterml.wml
    - owslib.wcs
    - owslib.wfs
    - owslib.wms
    - owslib.wmts
    - owslib.wps
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest tests
  requires:
    - pip
    - pytest
    - pytest-httpserver

about:
  home: https://github.com/geopython/OWSLib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OWSLib is a Python package for client programming with Open Geospatial Consortium (OGC)
    web service (hence OWS) interface standards, and their related content models.
  description: |
    OWSLib is a Python package for client programming with Open Geospatial Consortium (OGC)
    web service (hence OWS) interface standards, and their related content models.
    OWSLib was buried down inside PCL (Python Cartography Library), but has been brought out as a separate project.
  dev_url: https://github.com/geopython/OWSLib
  doc_url: https://owslib.readthedocs.io

extra:
  recipe-maintainers:
    - kalxas
    - tomkralidis
    - pelson
    - ocefpaf
