
{% set name = "OWSLib" %}
{% set version = "0.36.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/geopython/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 1aa07c28742dafbb8da070e8f6b2fbd5d2181ae86eb7dadf0bde2dae1b8c7515

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<312]

requirements:
  host:
    - pip
    - python
    - wheel
    # remove upper bound on setuptools to build pkg for py>312
    - setuptools
  run:
    - python
    - lxml
    - python-dateutil
    - pyyaml
    - requests

# Disable unstable test
{% set deselect_tests = " --deselect=tests/test_ogcapi_records_pycsw.py::test_ogcapi_records_pycsw" %}
test:
  source_files:
    - tests
  imports:
    - owslib
    - owslib.coverage
    - owslib.coverage.wcsBase
    - owslib.crs
    - owslib.csw
    - owslib.dif
    - owslib.etree
    - owslib.feature
    - owslib.feature.common
    - owslib.feature.postrequest
    - owslib.feature.schema
    - owslib.fes
    - owslib.fes2
    - owslib.fgdc
    - owslib.gm03
    - owslib.gml
    - owslib.iso
    - owslib.iso3
    - owslib.map.common
    - owslib.map.wms130
    - owslib.namespaces
    - owslib.ogcapi
    - owslib.ogcapi.connectedsystems
    - owslib.ogcapi.coverages
    - owslib.ogcapi.edr
    - owslib.ogcapi.features
    - owslib.ogcapi.maps
    - owslib.ogcapi.processes
    - owslib.ogcapi.records
    - owslib.opensearch
    - owslib.ows
    - owslib.owscontext.atom
    - owslib.owscontext.common
    - owslib.owscontext.core
    - owslib.owscontext.geojson
    - owslib.sos
    - owslib.swe.common
    - owslib.swe.observation.om
    - owslib.swe.observation.waterml2
    - owslib.util
    - owslib.waterml.wml
    - owslib.wcs
    - owslib.wfs
    - owslib.wms
    - owslib.wmts
    - owslib.wps
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests {{ deselect_tests }}
  requires:
    - pip
    - pytest
    - pytest-httpserver

about:
  home: https://github.com/geopython/OWSLib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OWSLib is a Python package for client programming with Open Geospatial Consortium (OGC)
    web service (hence OWS) interface standards, and their related content models.
  description: |
    OWSLib is a Python package for client programming with Open Geospatial Consortium (OGC)
    web service (hence OWS) interface standards, and their related content models.
    OWSLib was buried down inside PCL (Python Cartography Library), but has been brought out as a separate project.
  dev_url: https://github.com/geopython/OWSLib
  doc_url: https://owslib.readthedocs.io

extra:
  recipe-maintainers:
    - kalxas
    - tomkralidis
    - pelson
    - ocefpaf
