{% set version = "0.17.1" %}

package:
  name: owslib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/O/OWSLib/OWSLib-{{ version }}.tar.gz
  sha256: b2e7fd694d3cffcee79317bad492d60c0aa887aea6916517c051c3247b33b5a5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-dateutil
    - pytz
    - requests
    - pyproj
    - lxml

test:
  imports:
    - owslib.coverage
    - owslib.waterml
    - owslib.swe.observation
    - owslib.swe.sensor
    - owslib
    - owslib.feature
    - owslib.swe

about:
  home: https://geopython.github.io/OWSLib
  license: BSD-3-Clause
  # see https://github.com/geopython/OWSLib/pull/518
  #license_file: LICENSE
  summary: 'OGC Web Service utility library'

extra:
  recipe-maintainers:
    - kalxas
    - tomkralidis
    - pelson
    - ocefpaf
