{% set version = "0.19.0" %}

package:
  name: owslib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/O/OWSLib/OWSLib-{{ version }}.tar.gz
  sha256: 1d499981e13a1233822e94ee30c95ddd35d11f176e854d7f0cdc30ef55f5b065
  patches:
    # we can drop this when it is merged upstream
    - backport_635.patch

build:
  number: 2
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - pyproj
    - python-dateutil >=1.5
    - pytz
    - requests >=1.0

test:
  imports:
    - owslib
    - owslib.coverage
    - owslib.feature
    - owslib.swe
    - owslib.swe.observation
    - owslib.swe.sensor
    - owslib.waterml

about:
  home: https://geopython.github.io/OWSLib
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'OGC Web Service utility library'

extra:
  recipe-maintainers:
    - kalxas
    - tomkralidis
    - pelson
    - ocefpaf
