travis:
  secure:
    BINSTAR_TOKEN: fjMZKWFwZsp5p+ZwP+ucghgmCkNEgk9+7cvdFQsY3mOU82K+5+43o5Iw8HT3ypaN6YZHHaNzLOb4vf6v/TIgt8pqy+9wssskEzdTCNM3FSGnYUKr4e1dE1Iwnemdz5imRfZ53xYBKnda1kFHeRQAgTqN/ExLWd4wXVpPBo7INimGlhlSCkDXOfxh8v6hAMatRRKVFu1e3kqguz7s5JifpCKoM2z07ZZJiGfATLjlz6CUacXcQk1Hq1czEDwLHJPMpp4pZWKNrbel9f6Var/sIZBVmegNVlrwdFQYoqHjhySIshY/nuQIe1rhRe/zQy/Q/SPlg9xGqdivgtxII13hBsTUXmiXLzzrfLancsPQ8GtxlenlsNP6ImDdkElyLUKJMgSqtCZ5djb3NTDZm1o01gCo/JCxpCT/qOMMZGqGu2v1FPbj20fmIQcOh4kU9cg+7KIAo6JMMopiA88wN7pEKZW1PzsklfnHZv0UB9SZKv1kJnt4MeHaECp2g0WIa8hdA6nz1DURYXjDDTH8Ieg4w8f+0ztHEvQ8kO1zLyE3N/vH1L4B40o+7Fl6ZeNUK9313mCZDsZIb6OXNne0kFl6ZFogDI7QdhZiGtjTcaOA3GbnaN+9CEbOtyAJ9vfmIYF2XG079ypbAKrTgUKW0ryc7ZoZdxhjrk/Vw1GdqjUzfpg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
