travis:
  secure:
    BINSTAR_TOKEN: AOXtNhT8xWnbTJh/89pwuLFgy9ufs9TteK0pvbEwO8fBX3UDXgxRL5Q+fpr3fAtg9M++lKhvJR072wwnb8YoA3e/W7uW8mK1wxoFfOCbmkhMqsE5AIzJegKD23gvYSo6k0YIQZUGB13i1aSttwfvkTN0boXMrBzYiy4aefnz16jsv7sddOT0oOSvrXAgsPq+CCEjS0ke07Prce+2fwoAYk1eYZ0e+k6TXB+Vsl3+1eMi0Q6hFiRKeZOaRqS0Xh7nDMY5bv4Tl3HsMh6YBXZKEouR6uFcjzt6cOnYkwn07u+fuVtko6UR3Uc61uEbV8c+Titz2No3rgETseyWJ5oDr/hGAzW0JFwuBJGaBWCYjt38v0svk62J8EWVycmKlsBdYjPdLdjHqtyx02TRs8WpL/Kj+OdmEwMxl7WiAwsC+Vgu02dtkNAEJ+ma+I9QrDVSpoM8UuJW8LgfZ5LbJ9UdM6zV8SzrtlnwG2iY1fz6BbhM9IMCoBHiMpoDTnID3fW0xJZArrOmNACPSuyOyjRjvpybxcp0l9X6yOF/y0g56gPobWDSSH0MBc7wCszxkwdDH0rdGJvFhjD1+9yBNv2iLiiEbY2MJfsLcw0p6dNiFt6nwgThwUINUSR/QFG2iwH3T8DuPXAjDIX4JuX9MEVxLxzdDw1P2+wDYGgC3IfGG/k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
