travis:
  secure:
    BINSTAR_TOKEN: KtSB+wAaJeVJX/4vsM1Va+vjThZ9YTvpzSx3+5RciNDQq1Rx2Q6Ap9NswUQAc97AHGC1DbdhqJbl0FVCjB2RTw8WqQQUpO0os6UaNwpWd8tQSHOcv1/5TkGnKMiCwt2DxoAWPDJIBKHTMtl6MoHqqmjrTC7OZARxMpV0SrRTbWtnDxZuJn1RVzSCHpAIJH+8l2gFUerRHfToKIRbcoyjSmpgCwosdy2Za9k/b9fidjDJLlgLzeJrajlxnDdsmr/7Z8fBLuTLKGfBNmaWgw4W6cBVDdH7HDt+/A9FmWgc8wVaCdmme0xP3m3J1+QfXOQTuk9Lh2nBhzRbdWStjMciYn5ltTLrAHxBhQXoqd5EI4R5LZjL7T/DImN9TiAA6oFjf1wKKduHzjBVKufmmMKhPVFNcQHv5pkXEzI0abaRiqHmMmPxIzDtRBr0hHBlk1BwXSbcfDkQK7MMCygH0RogNEdtT7mdbAwCDNn7sYtTrSOgLnuD5mRmlmxD6sTyt9JP0MKTHscrBKD06/nL0tKptGrjoIj5dFCGFNYpfxXliMMJeGzpqKjQQe+4AYLODL67VYdL3dR8POtU9B6S99DkBRxPOKlFCG74e2POwL8wpmVi1V0aXfYkSn5rjXOztfOdcsWd9BQsDWIvXpXPf0zpUQmhUxyDbAhanYR9d1DD66M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
